language: objective-c
osx_image: xcode8.2
script:
    - xcodebuild test -scheme HexColors-iOS-Tests -sdk iphonesimulator -destination 'platform=iOS Simulator,id=86B2CA7C-0247-4257-BFEA-8035084AF2CF'
after_success:
  - bash <(curl -s https://codecov.io/bash)
